name: CI Pipeline

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
 
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt  

      - name: Run tests with coverage
        run: |
          pytest test.py -vv --cov=. --cov-report=xml --cov-report=term --disable-warnings 
        continue-on-error: false  

  
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Super-Linter
        uses: github/super-linter@v5
        env:
          DEFAULT_BRANCH: main
          VALIDATE_PYTHON_PYLINT: true  

 
  create_issues_from_todo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Scan for TODO comments
        id: find_todos
        run: |
          grep -rni 'TODO' . > todos.txt || echo "No TODOs found"
          if [[ -s todos.txt ]]; then
            echo "Found TODOs"
          else
            exit 0
          fi

      - name: Create Issues for TODOs
        if: ${{ steps.find_todos.outputs.has_todos != '' }}
        uses: JasonEtco/create-an-issue@v2
        with:
          filename: todos.txt

  deploy:
    uses: ./.github/workflows/deploy_testing_package.yml
